@startuml

hide circle

!define primary_key(x) <b><color:#b8861b><&key></color> x</b>
!define foreign_key(x) <color:#aaaaaa><&key></color> x
!define column(x) <color:#efefef><&media-record></color> x
!define table(x) entity x << (T, white) >>

table(veterinarians) {
    primary_key(vet_id): UUID <<PK>>
    --
    column(name): VARCHAR(100) NOT NULL
    column(specialty): VARCHAR(100) NOT NULL
    }

table(schedules) {
    primary_key(schedule_id): UUID <<PK>>
    foreign_key(pet_id)
    foreign_key(vet_id)
    --
    column(date_time): TIMESTAMP NOT NULL
    column(status): ENUM('scheduled', 'completed', 'cancelled')
    }

table(species) {
    primary_key(species_id): UUID <<PK>>
    --
    column(name): VARCHAR(50) NOT NULL
    column(description): TEXT
    }

table(breeds) {
    primary_key(breed_id): UUID <<PK>>
    foreign_key(species_id)
    --
    column(name): VARCHAR(50) NOT NULL
    }

veterinarians ||--o{ schedules
@enduml
